### ISSUE TITLE
error: index.ts:18 Uncaught ReferenceError: vue is not defined at index.ts:18.

### ISSUE THREAD

**Issue by oxzzx** [MMF-FE/vite-plugin-cdn-import#10]
modulesConfig add:
  "vue-router": {
    var: "vue-router",
    jsdeliver: {
      path: "dist/vue-router.global.prod.js"
    }
  },

error: index.ts:18 Uncaught ReferenceError: vue is not defined at index.ts:18.
18:  history: **createWebHashHistory(),**

I don't know why, can you fix it ?

**Comment by Jianazheng** [comment]
> modulesConfig add: "vue-router": { var: "vue-router", jsdeliver: { path: "dist/vue-router.global.prod.js" } },
> 
> error: index.ts:18 Uncaught ReferenceError: vue is not defined at index.ts:18. 18: history: **createWebHashHistory(),**
> 
> I don't know why, can you fix it ?
