### ISSUE TITLE
引入模块 不在包的根目录时，插件失效

### ISSUE THREAD

**Issue by casyalex** [MMF-FE/vite-plugin-cdn-import#20]
比如：
import * as PDFJS from 'pdfjs-dist/build/pdf.js'

externalGlobals 只把pdfjs-dist 当作key。并没有加入后面路径。

**Comment by Tansan-CC** [comment]
#19

**Comment by Tansan-CC** [comment]
这个问题已经定位到了。
https://github.com/MMF-FE/vite-plugin-cdn-import/blob/c37f095efe1456a081d521c7a90e7aef035f6057/src/index.ts#L130-L133
这里的`externalLibs`里面可以使用正则表达式，这样就可以把不在根目录的包整体在打包时排除。
我尝试解决这个问题，但是`externalGlobals`对这种不在根目录的包使用无效。
因此哪怕排除了也不能在打包后使用。
@vfasky

**Comment by MipaChan** [comment]
临时解决方案, 手动指定
``` javascript
export default defineConfig({
  // ...
  build: {
    rollupOptions: {
      external: [
        "pdfjs-dist/build/pdf.js",
      ],
      plugins: [
        externalGlobals({
          "pdfjs-dist/build/pdf.js",
        }),
      ],
    },
  },
)}
```

**Comment by Tansan-CC** [comment]
谢谢 @MipaChan
