### ISSUE TITLE
打包报错 TypeError: importToCDN is not a function

### ISSUE THREAD

**Issue by 1999-xinz** [MMF-FE/vite-plugin-cdn-import#22]
项目是vite搭建的vue3+Ts的模版，cdn引入就会报这个错误，不清楚是不是还需要配置什么，新人求助。
vite配置如下：
<img width="704" alt="image" src="https://user-images.githubusercontent.com/64197550/182411010-c8a24367-0798-463d-86a0-e1d5268a0570.png">
报错信息：
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/64197550/182413146-d7e9b4aa-a606-497f-8804-f95a7f98f226.png">

**Comment by airslice** [comment]
Try `import { Plugin as importToCDN } from "vite-plugin-cdn-import";`?

**Comment by AAsmallz** [comment]
> Try `import { Plugin as importToCDN } from "vite-plugin-cdn-import";`?

It's ready to pack and run, thank you

**Comment by Allenice** [comment]
Fixed in 1.x
