### ISSUE TITLE
在开发环境下也想使用cdn的方式怎么弄？

### ISSUE THREAD

**Issue by liuyinbin** [MMF-FE/vite-plugin-cdn-import#23]
> 我现在的项目配置是

  `importToCDN({
                modules:[
                    {
                        name:'vue',
                        var:'Vue',
                        path: 'https://cache.hzjiace.com/js/vue@3.2.16.global.js'
                    }
                ]
            }),`
但是这样的话在运行环境下是本地的路径

![image](https://user-images.githubusercontent.com/46306900/186550519-61b265e1-3f75-4fd2-81d3-abb62560f803.png)

打包后才是正确的引入路劲

**Comment by liuyinbin** [comment]
好吧，我看了源码，似乎是不支持在运行阶段的js cdn, 运行时就没有把配置的js路径做替换，只是做了css路径的替换

**Comment by liuyinbin** [comment]
但我还是想问下为什么要这样设置，这样就不好保证运行时和构建后的js的版本是一致的，虽然也可以做到一致，就是npm下载的版本和cdn的js版本自己设置为一致的,但是感觉还是不太方便！

**Comment by Allenice** [comment]
在 1.x 版本中使用 `enableInDevMode` 支持开发模式。
