### ISSUE TITLE
Would like to define attributes on demand

### ISSUE THREAD

**Issue by myst729** [MMF-FE/vite-plugin-cdn-import#24]
Attributes like `crossorigin` and `integrity` are very useful in regards of monitoring.
Also would like to have `defer` or other custom attributes define on demand.

**Comment by myst729** [comment]
https://github.com/MMF-FE/vite-plugin-cdn-import/pull/37

**Comment by joisun** [comment]
Hey, There is a example for set defer attribute:

```ts
// ...
  plugins: [
    vue(),
    cdn({
      generateScriptTag: (name, url) => ({ 
        attrs:{
          defer: true
        }
       }),
//...       
```

The same with async, hope it help anyone in need 😛
