### ISSUE TITLE
TypeError: importToCDN is not a function

### ISSUE THREAD

**Issue by Min888888** [MMF-FE/vite-plugin-cdn-import#27]
Ts 的使用情况是如何的？

**Comment by Min888888** [comment]
import importToCDN, { autoComplete } from 'vite-plugin-cdn-import';
xport default defineConfig({
  plugins: [ importToCDN({})]

我完全是照着示例在走，为什么会？

**Comment by tal007** [comment]
![image](https://user-images.githubusercontent.com/25813059/198944246-ab5e4ec8-4cc7-4de4-a251-6c36b385d116.png)
一样的

**Comment by Min888888** [comment]
你应该这样







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MMF-FE/vite-plugin-cdn-import"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MMF-FE/vite-plugin-cdn-import] TypeError: importToCDN is not a function (Issue #27)





 

 一样的

**Comment by JeasonLaung** [comment]
导入更改为
```js
import { Plugin as importToCDN } from 'vite-plugin-cdn-import'
```

就可以了

**Comment by 13970924891** [comment]
感谢大佬，我也刚好遇见一样的问题

**Comment by 13970924891** [comment]
我刚好也遇见这个bug，通过楼里大佬解决了，感谢

**Comment by Allenice** [comment]
1.x 版本已解决这个问题
