### ISSUE TITLE
cdn引用了，打包还是会打进去

### ISSUE THREAD

**Issue by shark-lajiao** [MMF-FE/vite-plugin-cdn-import#30]
![截图 2022-11-29 14-06-53](https://user-images.githubusercontent.com/86769380/204452348-e8cbd74f-c483-425a-a374-1f39b20cc7e0.png)
![截图 2022-11-29 14-07-39](https://user-images.githubusercontent.com/86769380/204452359-86d78290-2ca6-475c-ae6c-aec876b76250.png)
![截图 2022-11-29 14-08-37](https://user-images.githubusercontent.com/86769380/204452362-01038909-3d0c-42b5-8611-a432062bda89.png)

**Comment by Autumnwater** [comment]
结局了？
