### ISSUE TITLE
Support for module packages.

### ISSUE THREAD

**Issue by S-K-Tiger** [MMF-FE/vite-plugin-cdn-import#31]
This plugin loads all scripts with `<script src="${url}"></script>`. However this doesn't work for all packages.

Consider the following package: `"nayuki-qr-code-generator": "1.8.0"`. When 'imported' in this way you get the following error:
`Uncaught SyntaxError: export declarations may only appear at top level of a module`.

Could support for these types of packages be added?

----
Notes:

I've found I could get the desired result by manually adding the url source to the rollupOptions `{ rollupOptions: { external: ['https://unpkg.com/nayuki-qr-code-generator@1.8.0/index.js'] } }` and modifying the import to:
```ts
// This imports the script from the cdn. Included in the build by adding it to rollupOptions.external.
// @ts-expect-error 2300 2307
import qrcodegen from 'https://unpkg.com/nayuki-qr-code-generator@1.8.0/index.js';
// This part is marked as a type so it won't be included in the build but you can still use the type definitions.
// @ts-expect-error 2300
import type qrcodegen from 'nayuki-qr-code-generator';
```

**Comment by Allenice** [comment]
v1.x can use `generateScriptTag` option to customize the script tag
