### ISSUE TITLE
希望增加一个参数可以指定cdn插入的位置

### ISSUE THREAD

**Issue by lhlyu** [MMF-FE/vite-plugin-cdn-import#34]
类似这个 `injectTo?: 'head' | 'body' | 'head-prepend' | 'body-prepend'`，
默认`script`插入到`body`，`link`插入到`head`

**Comment by macheteHot** [comment]
https://github.com/MMF-FE/vite-plugin-cdn-import/blob/c37f095efe1456a081d521c7a90e7aef035f6057/src/index.ts#L154-L156
可以尝试提pr. 感觉作者不维护了?

**Comment by joisun** [comment]
Hey,There is an example to do with this,  hope it helps later came in guys! 😛

```ts
        cdn({
            modules: [ //... ],
            generateScriptTag(name, scriptUrl) {
                return {
                    injectTo: 'body-prepend',
                }
            },
```
