### ISSUE TITLE
js插入到</body>前比较好点

### ISSUE THREAD

**Issue by tabooc** [MMF-FE/vite-plugin-cdn-import#36]
index.ts 154行可以改一下
现在都加载到head里面了，一堆js文件，堵塞加载，失去了cdn的意义了

**Comment by Allenice** [comment]
v1.x 版本可以使用 `generateScriptTag` 参数自定义生成的标签和插入位置

**Comment by weijiatan456** [comment]
> v1.x 版本可以使用 `generateScriptTag` 参数自定义生成的标签和插入位置

能否来个demo？ @Allenice

**Comment by youthug** [comment]
> v1.x 版本可以使用 `generateScriptTag` 参数自定义生成的标签和插入位置

感觉应该支持在每个 module 配置更好，有些库需要提前引入，就用默认配置 `head-prepend`，其他就可设置为 `body` 避免影响加载
