### ISSUE TITLE
autoComplete("crypto-js") 出错

### ISSUE THREAD

**Issue by Piedpiper66** [MMF-FE/vite-plugin-cdn-import#39]
`crypto-js` 引入: `import CryptoJS from "crypto-js"`
用 vite 打包完后出现以下情况

![image](https://github.com/MMF-FE/vite-plugin-cdn-import/assets/39541338/60a9aa7d-38ca-4a83-b7b4-e0ec284f77a7)

![image](https://github.com/MMF-FE/vite-plugin-cdn-import/assets/39541338/74a315a4-eee6-45e6-8767-5e86304d0013)

原始
![image](https://github.com/MMF-FE/vite-plugin-cdn-import/assets/39541338/361c6115-2466-48e8-9345-83e2d782d0ab)

vite: `^4.2.1`
vite-plugin-cdn-import: `^0.3.5`

但是手动换成以下就没问题
```js
{
  name: "crypto-js",
  var: "CryptoJS",
  path: "https://cdn.jsdelivr.net/npm/crypto-js@4.1.1/crypto-js.min.js"
},
```

**Comment by Allenice** [comment]
可能是预设的路径错误了。1.0 版本去掉了 crypto-js，以后需要手动配置
