### ISSUE TITLE
TypeError: importToCDN is not a function

### ISSUE THREAD

**Issue by Mt-Youya** [MMF-FE/vite-plugin-cdn-import#42]
@MMF-FE
vite@4.4.5  TypeError: importToCDN is not a function

importToCDN必须.default 才能用
![1698203246014](https://github.com/MMF-FE/vite-plugin-cdn-import/assets/57708498/b64118e7-313e-4bbe-9443-e9b2a81c1562)
不用 default 用不了 
![1698203291440](https://github.com/MMF-FE/vite-plugin-cdn-import/assets/57708498/7e77a09d-6739-4249-b650-38da449a9e84)

**Comment by Mt-Youya** [comment]
@MMF-FE

**Comment by GuaiJieYo** [comment]
import { Plugin as importToCDN } from "vite-plugin-cdn-import";
这样引用试试

**Comment by nonzzz** [comment]
Why not try `vite-plugin-cdn2?`. This repository seems to be no longer maintained so I made a new plugin 
[vite-plugin-cdn2](https://github.com/nonzzz/vite-plugin-cdn)

**Comment by Mt-Youya** [comment]
> Why not try `vite-plugin-cdn2?`. This repository seems to be no longer maintained so I made a new plugin [vite-plugin-cdn2](https://github.com/nonzzz/vite-plugin-cdn)

I want to use Cloudflare CDN, could you add it in your url.js?
[Cloudflare CDN](https://cdnjs.com/) 
[libs](https://cdnjs.cloudflare.com/ajax/libs)

@nonzzz

**Comment by fxzer** [comment]
> Why not try `vite-plugin-cdn2?`. This repository seems to be no longer maintained so I made a new plugin [vite-plugin-cdn2](https://github.com/nonzzz/vite-plugin-cdn)

因为[vite-plugin-cdn2](https://github.com/nonzzz/vite-plugin-cdn)文档不完善，能自动导入哪些，有哪些配置想，每个配置项什么意思需要看源码才能看见呀，而且我试了您的插件，并未生效

**Comment by Allenice** [comment]
Fixed in 1.x
