### ISSUE TITLE
请问这种格式的怎么cdn啊

### ISSUE THREAD

**Issue by 360060316** [MMF-FE/vite-plugin-cdn-import#45]
import { basicSetup } from 'codemirror'
import { EditorView } from "@codemirror/view"
import { javascript } from '@codemirror/lang-javascript'
import { json } from '@codemirror/lang-json'
import { oneDark } from '@codemirror/theme-one-dark'

**Comment by Allenice** [comment]
使用 alias, 具体看 cdn 上这个包的链接，可以参考 react-dom 的配置 ：https://github.com/MMF-FE/vite-plugin-cdn-import/blob/master/src/autoComplete.ts#L25

**Comment by ChrisNi888** [comment]
没看懂，应该怎么写呢。比如这样引入的：
`import { Editor, Toolbar } from '@wangeditor/editor-for-vue'`
