### ISSUE TITLE
这种是不是不支持啊

### ISSUE THREAD

**Issue by 360060316** [MMF-FE/vite-plugin-cdn-import#46]
<script type="module"> import codemirror from https://cdn.jsdelivr.net/npm/codemirror@6.0.1/+esm </script>

{
          name: 'codemirror',
          var: 'codemirror',
          alias: ['codemirror', '@codemirror/view', '@codemirror/lang-javascript', '@codemirror/lang-json', '@codemirror/theme-one-dark'],
          path: [
            'https://cdn.jsdelivr.net/npm/codemirror@6.0.1/+esm',
            'https://cdn.jsdelivr.net/npm/@codemirror/view@6.26.3/+esm',
            'https://cdn.jsdelivr.net/npm/@codemirror/lang-javascript@6.2.2/+esm',
            'https://cdn.jsdelivr.net/npm/@codemirror/lang-json@6.0.1/+esm',
            'https://cdn.jsdelivr.net/npm/@codemirror/theme-one-dark@6.1.2/+esm']
        }
以上写法浏览器报错：Uncaught SyntaxError: Cannot use import statement outside a module (at +esm:7:1)

另外建议示例能不能把所有方法都列举一下 全是简单使用的方法，不需要示例的给示例了。。。。

**Comment by wanghaochun** [comment]
应该是，esm模块要插入标签后进行一次导入

**Comment by Allenice** [comment]
目前不支持 esm 格式
