### ISSUE TITLE
本来就是为了引入cdn减少包的体积的，为什么配置了之后还是把cdn的包也打包进来？

### ISSUE THREAD

**Issue by Minori-ty** [MMF-FE/vite-plugin-cdn-import#6]
本来就是为了引入cdn减少包的体积的，为什么配置了之后还是把cdn的包也打包进来？

**Comment by vfasky** [comment]
麻烦提供下 demo

**Comment by Minori-ty** [comment]
demo： https://github.com/Minori-ty/cdn-error-demo.git

**Comment by LuckyRyan-web** [comment]
在你的demo中，因为element-plus 需要全局引入样式文件，所以会把 woff 和 ttf 两个文件也一起打包，建议不要全局引入element的 css 文件，改为使用 cdn 引入,如下
![image](https://user-images.githubusercontent.com/28999580/129499240-a1cd0340-c80d-4ef8-babf-b97909ebd594.png)

**Comment by LuckyRyan-web** [comment]
> demo： https://github.com/Minori-ty/cdn-error-demo.git

在你的demo中，因为element-plus 需要全局引入样式文件，所以会把 woff 和 ttf 两个文件也一起打包，建议不要全局引入element的 css 文件，改为使用 cdn 引入,如下所示

![image](https://user-images.githubusercontent.com/28999580/129499517-6d8c0f8b-eaeb-4ec1-8cac-079afb0003de.png)

**Comment by Minori-ty** [comment]
> > demo： https://github.com/Minori-ty/cdn-error-demo.git
> 
> 在你的demo中，因为element-plus 需要全局引入样式文件，所以会把 woff 和 ttf 两个文件也一起打包，建议不要全局引入element的 css 文件，改为使用 cdn 引入,如下所示
> 
> ![image](https://user-images.githubusercontent.com/28999580/129499517-6d8c0f8b-eaeb-4ec1-8cac-079afb0003de.png)

你好，请问你可以跑一下我的demo吗？我现在是可以运行，但是打包报错

**Comment by LuckyRyan-web** [comment]
> > > demo： https://github.com/Minori-ty/cdn-error-demo.git
> > 
> > 
> > 在你的demo中，因为element-plus 需要全局引入样式文件，所以会把 woff 和 ttf 两个文件也一起打包，建议不要全局引入element的 css 文件，改为使用 cdn 引入,如下所示
> > ![image](https://user-images.githubusercontent.com/28999580/129499517-6d8c0f8b-eaeb-4ec1-8cac-079afb0003de.png)
> 
> 你好，请问你可以跑一下我的demo吗？我现在是可以运行，但是打包报错

你好，现在重新  yarn 一下就可以运行了

**Comment by Minori-ty** [comment]
> > > > demo： https://github.com/Minori-ty/cdn-error-demo.git
> > > 
> > > 
> > > 在你的demo中，因为element-plus 需要全局引入样式文件，所以会把 woff 和 ttf 两个文件也一起打包，建议不要全局引入element的 css 文件，改为使用 cdn 引入,如下所示
> > > ![image](https://user-images.githubusercontent.com/28999580/129499517-6d8c0f8b-eaeb-4ec1-8cac-079afb0003de.png)
> > 
> > 
> > 你好，请问你可以跑一下我的demo吗？我现在是可以运行，但是打包报错
> 
> 你好，现在重新 yarn 一下就可以运行了

![image](https://user-images.githubusercontent.com/79521943/129501613-cc8d3d02-e2ec-4ec5-8e1b-b344a6592656.png)
![image](https://user-images.githubusercontent.com/79521943/129501634-1d3c65d6-47ab-4521-ad44-84f73b8bc18b.png)
![image](https://user-images.githubusercontent.com/79521943/129501657-9b85fb21-c982-4928-962a-41447e9406c2.png)
配置了cdn，依旧是把js包引进来

**Comment by liukaigsx** [comment]
> > > > > demo： https://github.com/Minori-ty/cdn-error-demo.git
> > > > 
> > > > 
> > > > 在你的demo中，因为element-plus 需要全局引入样式文件，所以会把 woff 和 ttf 两个文件也一起打包，建议不要全局引入element的 css 文件，改为使用 cdn 引入,如下所示
> > > > ![image](https://user-images.githubusercontent.com/28999580/129499517-6d8c0f8b-eaeb-4ec1-8cac-079afb0003de.png)
> > > 
> > > 
> > > 你好，请问你可以跑一下我的demo吗？我现在是可以运行，但是打包报错
> > 
> > 
> > 你好，现在重新 yarn 一下就可以运行了
> 
> ![image](https://user-images.githubusercontent.com/79521943/129501613-cc8d3d02-e2ec-4ec5-8e1b-b344a6592656.png)
> ![image](https://user-images.githubusercontent.com/79521943/129501634-1d3c65d6-47ab-4521-ad44-84f73b8bc18b.png)
> ![image](https://user-images.githubusercontent.com/79521943/129501657-9b85fb21-c982-4928-962a-41447e9406c2.png)
> 配置了cdn，依旧是把js包引进来

同样配置了cdn，依旧是把js包引进来

**Comment by liukaigsx** [comment]
同样配置了cdn，依旧是把js包引进来

**Comment by liukaigsx** [comment]
回退到0.3.2可以了
`"vite-plugin-cdn-import": "0.3.2"`

**Comment by Minori-ty** [comment]
> 回退到0.3.2可以了
> `"vite-plugin-cdn-import": "0.3.2"`


> 回退到0.3.2可以了
> `"vite-plugin-cdn-import": "0.3.2"`

![image](https://user-images.githubusercontent.com/79521943/129513928-8f111b1f-b6c0-432c-b03e-3e63dfb46ca0.png)

降回0.3.2则一直打包报错，算了，不想折腾了，我已经找到另一种方式引入cdn了

**Comment by liukaigsx** [comment]
什么方式

**Comment by liukaigsx** [comment]
提了pr你康康

**Comment by Minori-ty** [comment]
> 提了pr你康康

![image](https://user-images.githubusercontent.com/79521943/129527873-c55cb781-de0d-43d4-a68e-7e0c57ac0bb0.png)

看了，打包不报错，不代表打包成功了。你有没有 npm run serve跑一下打包后的项目？

**Comment by liukaigsx** [comment]
可以了  index.min.js改成index.full.js

**Comment by Minori-ty** [comment]
> 可以了 index.min.js改成index.full.js

这次确实可以了，感谢帮助！

**Comment by Minori-ty** [comment]
> 什么方式

在build.rollupOptions.plugins.externalGlobals里面配置CDN
具体看我这个：https://github.com/Minori-ty/vite-model/blob/master/vite.config.js

**Comment by liukaigsx** [comment]
好的

**Comment by LuckyRyan-web** [comment]
> > 回退到0.3.2可以了
> > `"vite-plugin-cdn-import": "0.3.2"`
> 
> > 回退到0.3.2可以了
> > `"vite-plugin-cdn-import": "0.3.2"`
> 
> ![image](https://user-images.githubusercontent.com/79521943/129513928-8f111b1f-b6c0-432c-b03e-3e63dfb46ca0.png)
> 
> 降回0.3.2则一直打包报错，算了，不想折腾了，我已经找到另一种方式引入cdn了



> > > > > demo： https://github.com/Minori-ty/cdn-error-demo.git
> > > > 
> > > > 
> > > > 在你的demo中，因为element-plus 需要全局引入样式文件，所以会把 woff 和 ttf 两个文件也一起打包，建议不要全局引入element的 css 文件，改为使用 cdn 引入,如下所示
> > > > ![image](https://user-images.githubusercontent.com/28999580/129499517-6d8c0f8b-eaeb-4ec1-8cac-079afb0003de.png)
> > > 
> > > 
> > > 你好，请问你可以跑一下我的demo吗？我现在是可以运行，但是打包报错
> > 
> > 
> > 你好，现在重新 yarn 一下就可以运行了
> 
> ![image](https://user-images.githubusercontent.com/79521943/129501613-cc8d3d02-e2ec-4ec5-8e1b-b344a6592656.png)
> ![image](https://user-images.githubusercontent.com/79521943/129501634-1d3c65d6-47ab-4521-ad44-84f73b8bc18b.png)
> ![image](https://user-images.githubusercontent.com/79521943/129501657-9b85fb21-c982-4928-962a-41447e9406c2.png)
> 配置了cdn，依旧是把js包引进来

很抱歉，在0.3.2 版本没问题，但是 0.3.3版本会出现把 cdn 的包也打包进去的 bug ，现在0.3.4 版本已修复这个bug，可以在你的demo使用如下命令进行包的版本更新
```
yarn add vite-plugin-cdn-import -D
```

**Comment by Minori-ty** [comment]
> > > 回退到0.3.2可以了
> > > `"vite-plugin-cdn-import": "0.3.2"`
> > 
> > 
> > > 回退到0.3.2可以了
> > > `"vite-plugin-cdn-import": "0.3.2"`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/79521943/129513928-8f111b1f-b6c0-432c-b03e-3e63dfb46ca0.png)
> > 降回0.3.2则一直打包报错，算了，不想折腾了，我已经找到另一种方式引入cdn了
> 
> > > > > > demo： https://github.com/Minori-ty/cdn-error-demo.git
> > > > > 
> > > > > 
> > > > > 在你的demo中，因为element-plus 需要全局引入样式文件，所以会把 woff 和 ttf 两个文件也一起打包，建议不要全局引入element的 css 文件，改为使用 cdn 引入,如下所示
> > > > > ![image](https://user-images.githubusercontent.com/28999580/129499517-6d8c0f8b-eaeb-4ec1-8cac-079afb0003de.png)
> > > > 
> > > > 
> > > > 你好，请问你可以跑一下我的demo吗？我现在是可以运行，但是打包报错
> > > 
> > > 
> > > 你好，现在重新 yarn 一下就可以运行了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/79521943/129501613-cc8d3d02-e2ec-4ec5-8e1b-b344a6592656.png)
> > ![image](https://user-images.githubusercontent.com/79521943/129501634-1d3c65d6-47ab-4521-ad44-84f73b8bc18b.png)
> > ![image](https://user-images.githubusercontent.com/79521943/129501657-9b85fb21-c982-4928-962a-41447e9406c2.png)
> > 配置了cdn，依旧是把js包引进来
> 
> 很抱歉，在0.3.2 版本没问题，但是 0.3.3版本会出现把 cdn 的包也打包进去的 bug ，现在0.3.4 版本已修复这个bug，可以在你的demo使用如下命令进行包的版本更新
> 
> ```
> yarn add vite-plugin-cdn-import -D
> ```

好的
