### ISSUE TITLE
引入cdn的功能没问题，但是打包后的vendor依然有react

### ISSUE THREAD

**Issue by Hxgh** [MMF-FE/vite-plugin-cdn-import#7]
![image](https://user-images.githubusercontent.com/17973025/129860760-12b7e107-a0cd-4950-b21d-534de7ef84e1.png)

**Comment by LuckyRyan-web** [comment]
这个 bug 已处理，可以使用如下命令进行包版本更新
```
yarn add vite-plugin-cdn-import -D
or 
npm install vite-plugin-cdn-import --save-dev
```
