### ISSUE TITLE
如何解决css样式也被打包进去的问题？

### ISSUE THREAD

**Issue by Minori-ty** [MMF-FE/vite-plugin-cdn-import#8]
之前提了一个issue，js被打包进去的问题解决了，后来发现了另一个问题，就是打包后css也被打包进去了。
0.3.2可以只配置css的cdn链接，不在项目引入css样式，开发时有样式的效果。
但是升到0.3.4后，不仅要配置css的cdn链接，还要在项目中引入css样式，否则开发环境下看不到样式。

***这样的话，岂不是我每次重新打包，都要去main.js把css的代码注释掉？然后开发的时候，又把代码开启？***

配置如下：
![image](https://user-images.githubusercontent.com/79521943/130404786-dbc6386f-bf2d-4c77-ae57-d6f7064be0ad.png)
![image](https://user-images.githubusercontent.com/79521943/130404811-b736d432-aab2-460b-9937-c2fd3071acbb.png)
![image](https://user-images.githubusercontent.com/79521943/130404756-7297d1b0-00b2-4b34-a3ee-9edbadb19925.png)
![image](https://user-images.githubusercontent.com/79521943/130404878-8822ce0f-72d4-4436-b052-c0255181d862.png)

虽然没有引入css，但是打包有样式效果。不过如果想要在开发环境下开发，就去main.js配置css样式，这样又会把css给一起打包进来。
![image](https://user-images.githubusercontent.com/79521943/130405111-560c1ce6-46d8-4122-acd6-2fd9e798626d.png)
![image](https://user-images.githubusercontent.com/79521943/130405131-90610cdf-4f29-4dc8-9bdb-382453cd7b23.png)

**Comment by Minori-ty** [comment]
0.3.2可以只配置cdn，不引入css样式，开发时有样式的效果。但是有时会报错。
希望可以考虑结合0.3.2的功能，再做一次优化。

**Comment by LuckyRyan-web** [comment]
> 0.3.2可以只配置cdn，不引入css样式，开发时有样式的效果。但是有时会报错。
> 希望可以考虑结合0.3.2的功能，再做一次优化。

你好，你的demo地址还是https://github.com/Minori-ty/cdn-error-demo吗

**Comment by LuckyRyan-web** [comment]
> 0.3.2可以只配置cdn，不引入css样式，开发时有样式的效果。但是有时会报错。
> 希望可以考虑结合0.3.2的功能，再做一次优化。

你好，demo地址还是这个吗 `https://github.com/Minori-ty/cdn-error-demo`

**Comment by Minori-ty** [comment]
> > 0.3.2可以只配置cdn，不引入css样式，开发时有样式的效果。但是有时会报错。
> > 希望可以考虑结合0.3.2的功能，再做一次优化。
> 
> 你好，demo地址还是这个吗 `https://github.com/Minori-ty/cdn-error-demo`

是的，已经把demo上传上去了，你也可以把版本降回0.3.2测试看看

**Comment by LuckyRyan-web** [comment]
> > > 0.3.2可以只配置cdn，不引入css样式，开发时有样式的效果。但是有时会报错。
> > > 希望可以考虑结合0.3.2的功能，再做一次优化。
> > 
> > 
> > 你好，demo地址还是这个吗 `https://github.com/Minori-ty/cdn-error-demo`
> 
> 是的，已经把demo上传上去了，你也可以把版本降回0.3.2测试看看



> > > 0.3.2可以只配置cdn，不引入css样式，开发时有样式的效果。但是有时会报错。
> > > 希望可以考虑结合0.3.2的功能，再做一次优化。
> > 
> > 
> > 你好，demo地址还是这个吗 `https://github.com/Minori-ty/cdn-error-demo`
> 
> 是的，已经把demo上传上去了，你也可以把版本降回0.3.2测试看看

bug 已修复，你可以执行
```
yarn add vite-plugin-cdn-import -D
``` 
来进行升级

**Comment by Minori-ty** [comment]
> > > > 0.3.2可以只配置cdn，不引入css样式，开发时有样式的效果。但是有时会报错。
> > > > 希望可以考虑结合0.3.2的功能，再做一次优化。
> > > 
> > > 
> > > 你好，demo地址还是这个吗 `https://github.com/Minori-ty/cdn-error-demo`
> > 
> > 
> > 是的，已经把demo上传上去了，你也可以把版本降回0.3.2测试看看
> 
> > > > 0.3.2可以只配置cdn，不引入css样式，开发时有样式的效果。但是有时会报错。
> > > > 希望可以考虑结合0.3.2的功能，再做一次优化。
> > > 
> > > 
> > > 你好，demo地址还是这个吗 `https://github.com/Minori-ty/cdn-error-demo`
> > 
> > 
> > 是的，已经把demo上传上去了，你也可以把版本降回0.3.2测试看看
> 
> bug 已修复，你可以执行
> 
> ```
> yarn add vite-plugin-cdn-import -D
> ```
> 
> 来进行升级

好的，确实可以了，谢谢
