### ISSUE TITLE
关于0.3.5在开发环境时也引入cdn的问题

### ISSUE THREAD

**Issue by Minori-ty** [MMF-FE/vite-plugin-cdn-import#9]
我又来了，一起把这个插件变得更加完善把！
我在公司开发时。项目引用了很多包的css cdn，但是我启动的时候发现在开发环境下，css的cdn反而阻塞了渲染的速度，也就是说这个渲染速度没有本地加载css快。所以我觉得在开发环境下也引入cdn不太合适。
我想要达到的功能是： 我在main.js中引入css，然后开发环境下是用的是我本地引入的css。到了生产打包的时候，这个插件能够自动移除引入的css，并且在index.html中引入cdn的css。
当然这个插件目前已经达到了后者，现在只需要区分在生产打包时移除引入的css包就行了。

**Comment by LuckyRyan-web** [comment]
> 我又来了，一起把这个插件变得更加完善把！
> 我在公司开发时。项目引用了很多包的css cdn，但是我启动的时候发现在开发环境下，css的cdn反而阻塞了渲染的速度，也就是说这个渲染速度没有本地加载css快。所以我觉得在开发环境下也引入cdn不太合适。
> 我想要达到的功能是： 我在main.js中引入css，然后开发环境下是用的是我本地引入的css。到了生产打包的时候，这个插件能够自动移除引入的css，并且在index.html中引入cdn的css。
> 当然这个插件目前已经达到了后者，现在只需要区分在生产打包时移除引入的css包就行了。

这个问题的话，建议使用 jsdelivr 的配置，因为 jsdelivr 在国内的访问速度还是比较快的。
